services:
  # Service Aplikasi Laravel dengan FrankenPHP
  app:
    build:
      context: .
      dockerfile: docker/frankenphp/Dockerfile # Path ke Dockerfile FrankenPHP
    restart: unless-stopped
    ports:
      - "${APP_PORT:-80}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
      - "443:443" # Port untuk HTTPS jika dibutuhkan
    volumes:
      # Mounting kode ke /app, direktori kerja di container FrankenPHP
      - .:/app:rw,cached
    depends_on:
      - mysql
      - redis
      - meilisearch
      - mailpit
      - selenium
    networks:
      - sail

  # --- SERVICE LAINNYA TIDAK BERUBAH ---
mysql:
  image: 'mysql/mysql-server:8.0'
  ports:
    - '${FORWARD_DB_PORT:-3306}:3306'
  environment:
    MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
    MYSQL_ROOT_HOST: '%'
    MYSQL_DATABASE: '${DB_DATABASE:-laravel}'
    MYSQL_USER: '${DB_USERNAME:-sail}'
    MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  volumes:
    - 'sail-mysql:/var/lib/mysql'
  networks:
    - sail
  healthcheck:
    test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD:-password}"]
    retries: 3
    timeout: 5s
  command: --default-authentication-plugin=mysql_native_password --skip-host-cache --skip-name-resolve

  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'sail-redis:/data'
    networks:
      - sail
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

  meilisearch:
    image: 'getmeili/meilisearch:latest'
    ports:
      - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    environment:
      MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
    volumes:
      - 'sail-meilisearch:/meili_data'
    networks:
      - sail
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://127.0.0.1:7700/health"]
      retries: 3
      timeout: 5s

  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - sail

  selenium:
    image: selenium/standalone-chromium
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - '/dev/shm:/dev/shm'
    networks:
      - sail

networks:
  sail:
    driver: bridge

volumes:
  sail-mysql:
    driver: local
  sail-redis:
    driver: local
  sail-meilisearch:
    driver: local